[package]
name = "sm_sys"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.20"
term_size = "0.3"
colored = "2.0"
csv = "1.3"
lettre = "0.11"
tokio = { version = "1", features = ["full"] }
